name: Android Build ## name of the workflow

on:
  workflow_dispatch: # To trigger manual build

  release:
    types: [published] # only run the workflow when a new release has been published

  pull_request:
    branches:
      - main

jobs:
  android-build:
    name: Android Build

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository

        uses: actions/checkout@v2

      - name: Set up our JDK environment

        uses: actions/setup-java@v1.4.3

        with:
          java-version: 11

      - name: Install dependencies

        run: yarn install

      - name: Run Linter

        run: yarn lint

      - name: Run Tests

        run: yarn test

      - name: Make Gradlew Executable

        run: cd android && chmod +x ./gradlew

      - name: Generate App APK

        run: |

          cd android && ./gradlew assembleRelease

      - name: Sign APK

        id: sign_app

        uses: r0adkll/sign-android-release@v1

        with:
          releaseDirectory: android/app/build/outputs/apk/release

          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}

          alias: ${{ secrets.ANDROID_ALIAS }}

          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}

          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: upload artifact to Firebase App Distribution

        uses: wzieba/Firebase-Distribution-Github-Action@v1

        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}

          token: ${{secrets.ANDROID_FIREBASE_TOKEN}}

          groups: testers

          file: ${{steps.sign_app.outputs.signedReleaseFile}}
