name: CD Android ## name of the workflow

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  cd-android:
    name: CD Android

    runs-on: ubuntu-latest

    steps:
      steps:
        - name: Download artifact

          uses: actions/github-script@v6

          with: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "artifact_signed"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact_signed.zip`, Buffer.from(download.data));

        - name: Unzip artifact

          id: unzip_artifact

          run: unzip artifact_signed.zip

        - name: upload artifact to Firebase App Distribution

          uses: wzieba/Firebase-Distribution-Github-Action@v1

          with:
            appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}

            token: ${{secrets.ANDROID_FIREBASE_TOKEN}}

            groups: testers

            file: ${{steps.unzip_artifact.outputs.artifact_signed}}
